version: '3.8'
services:
    mongodb_container:
        image: mongo:latest
        env_file:
            - .env
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

volumes:
    mongodb_data_container:
